<?php
/**
 * This file is part of the NewVisionAirportsBundle.
 *
 * (c) Nikolay Tumbalev <n.tumbalev@newvision.bg>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace NewVision\AirportsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use NewVision\PublishWorkflowBundle\PublishWorkflowQueryBuilderTrait;
/**
 * Custom methods for working with Entity
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package NewVisionAirportsRepository
 * @author  Nikolay Tumbalev <n.tumbalev@newvision.bg>
 */
class AirportRepository extends EntityRepository
{
    use PublishWorkflowQueryBuilderTrait;

    /**
     * Find all by locale
     * @var locale string
     * @var limit integer
     * @var offset integer
     * @return array
     */
    public function findAllByLocale($locale, $limit = null, $offset = null)
    {
        $qb = $this->getPublishWorkFlowQueryBuilder();
        $qb
            ->leftJoin('c.translations', 't')
            ->andWhere('t.locale = :locale')
            ->andWhere('t.title IS NOT NULL')
            ->setParameter('locale', $locale)
            ->setParameter('now', new \DateTime())
            ->setMaxResults($limit)
            ->setFirstResult($offset);
        $query = $qb->getQuery();

        return $query->getResult();
    }

    /**
     * Find all by locale
     * @var locale string
     * @var limit integer
     * @var offset integer
     * @return array
     */
    public function findHomepageAirports($locale, $limit = null, $offset = null)
    {
        $qb = $this->getPublishWorkFlowQueryBuilder();
        $qb
            ->leftJoin('c.translations', 't')
            ->andWhere('t.locale = :locale and c.isHomepage = :homepage')
            ->andWhere('t.title IS NOT NULL')
            ->setParameter('locale', $locale)
            ->setParameter('homepage', 1)
            ->setParameter('now', new \DateTime())
            ->orderBy('c.rank', 'ASC')
            ->setMaxResults($limit)
            ->setFirstResult($offset);
        $query = $qb->getQuery();

        return $query->getResult();
    }

    /**
     * Find one news by slug and locale
     * @var string $slug
     * @var string $locale
     * @return array
     */
    public function findOneBySlugAndLocale($slug, $locale)
    {
        $qb = $this->getPublishWorkFlowQueryBuilder(null);
        $qb
            ->leftJoin('c.translations', 't')
            ->andWhere('t.locale = :locale')
            ->andWhere('t.slug = :slug')
            ->andWhere('t.title IS NOT NULL')
            ->setParameter('slug', $slug)
            ->setParameter('locale', $locale)
            ->setParameter('now', new \DateTime());
        $query = $qb->getQuery();

        return $query->getOneOrNullResult();
    }

    /**
     * Find all by airportCategory and locale
     * @var airportCategoryId integer
     * @var locale string
     * @var limit integer
     * @var offset integer
     * @return array
     */
    public function findAllByCategoryAndLocale($airportCategoryId, $locale, $limit = null, $offset = null)
    {
        $qb = $this->getPublishWorkFlowQueryBuilder();
        $qb
            ->leftJoin('c.translations', 't')
            ->leftJoin('c.airportCategories', 'cat')
            ->andWhere('t.locale = :locale')
            ->andWhere('t.slug IS NOT NULL')
            ->andWhere('cat.id = :airportCategoryId')
            ->andWhere('t.title IS NOT NULL')
            ->setParameter('airportCategoryId', $airportCategoryId)
            ->setParameter('locale', $locale)
            ->setParameter('now', new \DateTime())
            ->orderBy('c.rank', 'ASC')
            ->setFirstResult($offset)
            ->setMaxResults($limit);
        $query = $qb->getQuery();

        return $query->getResult();
    }

    /**
     * Query for airports listing
     * @var airportCategoryId integer
     * @var locale string
     * @var limit integer
     * @var offset integer
     * @return array
     */
    public function getAirportsListingQuery($airportCategoryId, $locale, $page, $pageSize)
    {
        $qb = $this->getPublishWorkFlowQueryBuilder(null);
        $qb
            ->leftJoin('c.translations', 't')
            ->leftJoin('c.airportCategories', 'cat')
            ->andWhere('t.locale = :locale')
            ->andWhere('t.slug IS NOT NULL')
            ->andWhere('t.title IS NOT NULL');
            if ($airportCategoryId === null) {
                $qb->andWhere('cat.id IS NULL');
            } else {
                $qb
                    ->andWhere('cat.id = :airportCategoryId')
                    ->setParameter('airportCategoryId', $airportCategoryId)
                ;
            }
        $qb
            ->setParameter('locale', $locale)
            ->orderBy('c.rank', 'ASC')
            ->setFirstResult($pageSize * ($page-1))
            ->setMaxResults($pageSize);

        return $qb->getQuery();
    }

    /**
     * Find all by category and locale
     * @var categoryId integer
     * @var airportId integer
     * @var locale string
     * @var limit integer
     * @var offset integer
     * @return array
     */
    public function findSameCategoryAirports($airportCategoryId, $airportId, $locale, $limit = null, $offset = null)
    {
        $qb = $this->getPublishWorkFlowQueryBuilder();
        $qb
            ->leftJoin('c.translations', 't')
            ->leftJoin('c.airportCategories', 'cat')
            ->andWhere('t.locale = :locale')
            ->andWhere('t.slug IS NOT NULL')
            ->andWhere('t.title IS NOT NULL')
            ->andWhere('cat.id = :airportCategoryId')
            ->andWhere('c.id != :airportId')
            ->setParameter('airportCategoryId', $airportCategoryId)
            ->setParameter('airportId', $airportId)
            ->setParameter('locale', $locale)
            ->setParameter('now', new \DateTime())
            ->orderBy('c.rank', 'ASC')
            ->setFirstResult($offset)
            ->setMaxResults($limit);
        $query = $qb->getQuery();

        return $query->getResult();
    }
}
